### ISSUE TITLE
does work for f24

### ISSUE THREAD

**Issue by Vilegent** [damaestro/openconnect-juniper-rpm#1]
worked great for f23 but doesnt work for f24
returns XML responce has no "auth" node

**Comment by damaestro** [comment]
@Vilegent thanks for letting me know. I'll take a look at f24 soon as I'm currently using it with f23 without issue. It's possible there was an update I have not been tracking.

**Comment by Vilegent** [comment]
yes the issue with f24 is that openconnect         x86_64         7.07-2.fc24  is in Fedora updates and your  version is 7.06

**Comment by damaestro** [comment]
@Vilegent I've built an updated build from 7.07 in copr.
